name: WordPress Coding Standards

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require "wp-coding-standards/wpcs"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Run PHPCS
        run: phpcs --standard=WordPress .
